config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'users#new'

  get "pages/impressum", :as => 'impressum'

  get "pages/anfrag_sp", :as => 'anfrag_sp'

  get "pages/anfragen", :as => 'anfragen'

  get "pages/daten", :as => 'daten'

  get "pages/inbox", :as => 'inbox'

  get "users/success", :as => 'success'

  get "pages/spieler_search", :as => 'spieler_search'

  get "pages/kond", :as => 'kond'

  get "pages/match", :as => 'match'

  get "pages/match_sp", :as => 'match_sp'

  get "pages/mes", :as => 'mes'

  get "pages/mes2", :as => 'mes2'

  get "pages/passwort", :as => 'passwort'

  get "pages/prof_sp", :as => 'prof_sp'

  get "pages/profil_sp", :as => 'profil_sp'

  get "pages/profil_ver", :as => 'profil_ver'

  get "pages/soc", :as => 'soc'

  get "pages/sp_res", :as => 'sp_res'

  get "pages/thanks", :as => 'thanks'

  get "pages/ver_pr", :as => 'ver_pr'

  get "pages/ver_res", :as => 'ver_res'

  get "pages/verein_search", :as => 'verein_search'

  get "pages/vertrag", :as => 'vertrag'

  if Rails.env.production?
    get '400', :to => 'errors#already_exists'
    get '404', :to => 'errors#page_not_found'
    get '422', :to => 'errors#server_error'
    get '500', :to => 'errors#server_error'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  after_create :subscribe_user_to_mailing_list
  #after_create :send_welcome_email_to_user


  def send_welcome_email_to_user
    UserMailer.welcome_email(self).deliver_later
  end

  private

    def subscribe_user_to_mailing_list
      SubscribeUserToMailingListJob.perform_now(self)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  http_basic_authenticate_with :name => "development", :password => "knoblauch99", if: :authenticate?

  private

    def authenticate?
      if ((controller_name == 'pages' && %w( daten impressum).include?(action_name)) || (controller_name == 'users'))
        false
      else
        true
      end
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def page_not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found_error', layout: 'layouts/application', status: 404 }
      format.all  { render nothing: true, status: 404 }
    end
  end

  def already_exists
    respond_to do |format|
      format.html { render template: 'errors/already_exists', layout: 'layouts/application', status: 400 }
      format.all  { render nothing: true, status: 400 }
    end
  end

  def server_error
    respond_to do |format|
      format.html { render template: 'errors/internal_server_error', layout: 'layouts/error', status: 500 }
      format.all  { render nothing: true, status: 500}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def daten

  end

  def impressum

  end


  def passwort

  end

  def soc

  end

  def thanks

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show

  end

  def daten
    render template: "users/daten"
  end

  def impressum
    render template: "users/impressum"
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    render "users/success"
    else
      render "errors/already_exists"
    end
  end

  def index
    @users = User.all
  end
  

  private

    def user_params
      params.require(:user).permit(:email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LandingPage</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>	
		<%= yield %>
</body>
</html>

app/views/pages/anfrag_sp.html.haml
#wrapp  
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/pages/soc", :rel => "home", :title => "Soccertransfair"}
          %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;"}
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "#"} Home
          %li
            = link_to 'Suche  Spieler', sp_res_url 
          %li
            = link_to 'Suche Verein', ver_res_url 
          %li#log
            %a{:href => "/pages/inbox"} Nachrichten
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Profil
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "/pages/ver_pr"} Profil bearbeiten
              %li
                %a{:href => "/pages/passwort"} Kontoeinstellungen
              %li
                %a{:href => "/pages/match"} Matchings
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Logout
  .container-fluid
    .row#main_row
      .col-md-12
        %h1.name_page Anfragen
  .container-fluid
    .row
      .col-md-6.col-md-offset-3
        %form#anfragen
          .form-group.col-lg-1.col-md-3.col-sm-2.col-xs-9.col-xs-offset-3
            %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_565,w_565/v1461938985/spi_image_p9lj62.png", :style => "max-width:120px"}
          .form-group.col-md-7.col-lg-4.col-sm-4.col-xs-9.col-xs-offset-2{:style=> "font-size:14pt"}
            %b Name
            %br
            %b Position: 
            Torh&uuml;ter 
            %br 
            %b Alter: 
            28
            %br 
            %b Aktuelle Liga: 
            Regional
            %br 
            %b Ort: 
            Berlin
            %br
            %b Starker Fuß: 
            Rechts
          .form-group.row
            .col-md-6.col-md-offset-3.col-lg-5.col-lg-offset-6.col-sm-4.col-sm-offset-7.col-xs-9.col-xs-offset-2
              Hiermit akzeptiere ich die
              .checkbox
                %label{:for=>"check_ver"}
                  %input#check_ver{:type => "checkbox",:style=>"position:relative"}
                %a{:href => "/pages/vertrag"}Vertragsbedingungen
              .checkbox
                %label
                  %input{:type => "checkbox",:style=>"position:relative"}
                %a{:href => "/pages/kond"} Konditionen
              von soccertransfair.com
            .col-md-2.col-md-offset-6.col-xs-5.col-xs-offset-1
              %a.btn.btn-default{"data-target" => "#anfrag", "data-toggle" => "modal"} Anfragen
            .col-md-2.col-sm-2
              %a.btn.btn-default.abbre{:href=>"/pages/sp_res"} Abbrechen
#anfrag.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %strong#myModalLabel.modal-title  Vielen Dank!
      .modal-body
        %p{:style=>"font-size:14pt; text-align:justify"}Ihre Anfrage wurde erfolgreich &uuml;bermittelt. Sie werden informiert sobald der Spieler Ihre Anfrage best&auml;tigt hat.
        %a.btn.btn-default#zuruck{:href=>"/pages/sp_res"} Zur&uuml;ck zur Suche

app/views/pages/anfragen.html.haml
#wrapp  
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/pages/soc", :rel => "home", :title => "Soccertransfair"}
          %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;"}
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "/pages/soc"} Home
          %li
            = link_to 'Suche  Spieler', sp_res_url 
          %li
            = link_to 'Suche Verein', ver_res_url 
          %li#log
            %a{:href => "/pages/inbox"} Nachrichten
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Profil
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "/pages/ver_pr"} Profil bearbeiten
              %li
                %a{:href => "/pages/passwort"} Kontoeinstellungen
              %li
                %a{:href => "/pages/match"} Matchings
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Logout
  .container-fluid
    .row#main_row
      .col-md-12
        %h1.name_page Anfragen
  .container-fluid
    .row
      .col-md-6.col-md-offset-3
        %form#anfragen
          .form-group.col-lg-1.col-md-3.col-sm-2.col-xs-9.col-xs-offset-3
            %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:120px"}
          .form-group.col-md-7.col-lg-4.col-sm-4.col-xs-9.col-xs-offset-2{:style=> "font-size:14pt"}
            %b Vereinsname:
            %br
            %b Aktuelle Liga: 
            Regional
            %br 
            %b Ort: 
            Berlin
          .form-group.row
            .col-md-6.col-md-offset-3.col-lg-5.col-lg-offset-6.col-sm-4.col-sm-offset-7.col-xs-9.col-xs-offset-2
              Hiermit akzeptiere ich die
              .checkbox
                %label{:for=>"check_ver"}
                  %input#check_ver{:type => "checkbox",:style=>"position:relative"}
                %a{:href => "/pages/vertrag"}Vertragsbedingungen
              .checkbox
                %label
                  %input{:type => "checkbox",:style=>"position:relative"}
                %a{:href => "/pages/kond"} Konditionen
              von soccertransfair.com
            .col-md-2.col-md-offset-6.col-xs-5.col-xs-offset-1
              %a.btn.btn-default{"data-target" => "#anfrag", "data-toggle" => "modal"} Anfragen
            .col-md-2.col-md-2.col-sm-2
              %a.btn.btn-default.abbre{:href=>"/pages/ver_res"} Abbrechen
#anfrag.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %strong#myModalLabel.modal-title  Vielen Dank!
      .modal-body
        %p{:style=>"font-size:14pt; text-align:justify"}Ihre Anfrage wurde erfolgreich &uuml;bermittelt. Sie werden informiert sobald der Verein Ihre Anfrage best&auml;tigt hat.
        %a.btn.btn-default#zuruck{:href=>"/pages/ver_res"} Zur&uuml;ck zur Suche

app/views/pages/impressum.html.haml
.nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/", :rel => "home", :title => "Soccertransfair"}
        %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;", }
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Startseite', root_path
        %li
          = link_to 'Datenschutzerklärung', daten_url
.container-fluid
  .row#main_row
    .col-md-12
      %h1.name_page Impressum
  .row#leftone
    .col-md-12
      %h2
        Angaben gem&auml;&szlig; &sect; 5 TMG:
      UG (haftungsbeschränkt)
      %br
      Hardenbergstr 38
      %br
      10713 Berlin
      %h2
        Vertreten durch:
      [Vertreten durch: Name, Anschrift]
      %br
      %h2
        Kontakt:
      Telefon: +49 (0) 30 36623723674
      %br
      Telefax: +49 (0) 30 36623723675
      %br
      E-Mail: tom@soccertransfair.de
      %br
      %h2
        Registereintrag:
      Eintragung im Handelsregister.
      %br
      Registergericht:Amtsgericht Berlin
      %br
      Registernummer: 2423423423
      %br
      %h2
        Umsatzsteuer-ID:
      Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz: 35345345345523
      %br
      %h2
        Aufsichtsbehörde:
      Berlin
      %br
      %br
  

app/views/pages/ver_pr.html.haml
#wrapp  
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/pages/soc", :rel => "home", :title => "Soccertransfair"}
          %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;", }
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "/pages/soc"} Home
          %li
            %a{:href => "/pages/sp_res"} Suche  Spieler
          %li
            %a{:href => "/pages/ver_res"} Suche Verein
          %li#log
            %a{:href => "/pages/inbox"} Nachrichten
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Profil
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "/pages/profil_ver"} Profil bearbeiten
              %li
                %a{:href => "/pages/passwort"} Kontoeinstellungen
              %li
                %a{:href => "/pages/match"} Matchings
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Logout
  .container-fluid
    .row#main_row
      .col-md-12
        %h1.name_page Profil
  .container-fluid#messa
    .row
      .col-md-2.col-md-offset-1.col-sm-4
        %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:210px"}
      .col-md-2.hidden-xs.hidden-sm
        %a{"data-placement" => "right", "data-toggle" => "tooltip", :title => "Videos, Bilder und der sportliche Lebenslauf können nur nach erfolgreichem Matching vom jeweiligem Verein eingesehen werden.", :rel => "tooltip", :href => "#"}
          %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1462526860/question_zo2rqm.png", :style => "max-width:20px", }
      .col-md-3
        .form-group
          %input#Email1.form-control{:placeholder => "Vereinsname", :type => "text"}
          %input#Password1.form-control{:placeholder => "PLZ", :type => "text"}
          %input#Email1.form-control{:placeholder => "Ort", :type => "text"}
          %input#Password1.form-control{:placeholder => "Adresse", :type => "text"}
          %select.form-control
            %option{:disabled => "", :hidden => "", :selected => "", :value => ""} Liga 1.Team
            %option{:value => "tow"} Ebene1
            %option{:value => "def"} Ebene2
            %option{:value => "mit"} Ebene3
            %option{:value => "off"} Ebene4
      .col-md-3
        %input#Email1.form-control{:placeholder => "Kontaktperson Herren", :type => "text"}
        %input#Password1.form-control{:placeholder => "Kontaktperson Jugend", :type => "text"}
        %input#Email1.form-control{:placeholder => "E-Mail", :type => "email"}
        %input#Password1.form-control{:placeholder => "Telefon", :type => "text"}
        %input#Password1.form-control{:placeholder => "Website", :type => "url"}
    .row
      .col-md-3.col-md-offset-5
        .checkbox{:style => "text-align: left;"}
          %label
            %input{:type => "checkbox"}
              Ich akzeptiere die AGBs
      .col-md-3
        %a.btn.btn-primary.btn-lg.btn-block{:href => "#"}Speichern
    .row{:style => "margin-top:10px"}
      .col-md-10.col-md-offset-1
        %textarea.form-control{:rows => "8", :placeholder => "Beschreibung"}
  .container-fluid
    .row
      .col-md-10.col-md-offset-1
        #no-more-tables
          %table.table.table-striped.table-bordered{:style => "font-size: 15pt;"}
            %tr
              %td.col-md-4
                Bundesliga
              %td.col-md-6 
                Mannschaft
              %td.col-md-2#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "#"}L&ouml;schen
            %tr
              %td
                Bundesliga
              %td 
                Mannschaft
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "#"}L&ouml;schen
            %tr
              %td
                Bundesliga
              %td 
                Mannschaft
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "#"}L&ouml;schen
  .container-fluid
    .row
      .col-md-3.col-md-offset-8
        %a.btn.btn-primary.btn-lg.btn-block{"data-target" => "#teams", "data-toggle" => "modal",  :style => "margin:9px 3px;"} Mannschaft hinzuf&uuml;gen
  .container-fluid#footer
    %a.navbar-brand{:href => "#", :rel => "home", :title => "Soccertransfair"}
      %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;"}
    .row
      .col-md-2.col-md-offset-8.col-xs-12
        = link_to 'Impressum', impressum_url , class: "main_link"
        = link_to 'Datenschutzerklärung', daten_url, class: "main_link"
#teams.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %strong#myModalLabel.modal-title  Mannschaft hinzuf&uuml;gen
      .modal-body
        %form
          .form-group
            %select.form-control
              %option{:disabled => "", :hidden => "", :selected => "", :value => ""} Liga
              %option{:value => "liga"} Bla
              %option{:value => "liga"} Bla
            %select.form-control
              %option{:disabled => "", :hidden => "", :selected => "", :value => ""} Mannschaft
              %option{:value => "team"} Bla
              %option{:value => "team"} Bla

            %button.btn.btn-primary.btn-lg.btn-block{:type => "submit", :style => "margin-top:3px;"} Speichern

app/views/pages/ver_res.html.haml
#wrapp  
  %nav.navbar.navbar-default.navbar-fixed-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => "/pages/soc", :rel => "home", :title => "Soccertransfair"}
          %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;"}
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "/pages/soc"} Home
          %li
            = link_to 'Suche  Spieler', sp_res_url 
          %li.active
            %a{:href => "/pages/verein_search"} Suche Verein 
          %li
            %a{:href => "/pages/inbox"} Nachrichten
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Profil
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "/pages/ver_pr"} Profil bearbeiten
              %li
                %a{:href => "/pages/passwort"} Kontoeinstellungen
              %li
                %a{:href => "/pages/match"} Matchings
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Logout
  .container-fluid
    .row#main_row
      .col-md-12
        %h1.name_page Wir haben passende Vereine f&uuml;r Sie gefunden!
  %form
    .container-fluid
      .row#results
        .col-md-2.col-md-offset-2.col-sm-6.col-xs-12
          %input#altvon.form-control{:placeholder => "PLZ", :type => "text"}
        .col-md-2.col-sm-6.col-xs-12
          %select.form-control
            %option{:disabled => "", :hidden => "", :selected => "", :value => ""} Umkreis
            %option{:value => "tow"} +5
            %option{:value => "def"} +10
            %option{:value => "mit"} +15
            %option{:value => "off"} +20 
        .col-md-2.col-sm-6.col-xs-12           
          %select.form-control
            %option{:disabled => "", :hidden => "", :selected => "", :value => ""} Liga 1.Team
            %option{:value => "tow"} Ebene1
            %option{:value => "def"} Ebene2
            %option{:value => "mit"} Ebene3
            %option{:value => "off"} Ebene4
        .col-md-2.col-sm-6.col-xs-12
          %button.btn.btn-primary.btn-lg.btn-block#suchen_b{:type => "submit"} Suchen
  .container-fluid
    .row
      .col-md-6.col-md-offset-3
        #no-more-tables
          %table.table.table-bordered.table-striped{:style => "font-size: 15px;"}
            %tr
              %td.col-md-2
                %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:100px"}
              %td.col-md-7 
                %b Vereinsname
                %br
                %b Aktuelle Liga: 
                Regional
                %br 
                %b Ort: 
                Berlin
              %td.col-md-3#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "/pages/anfragen"} Anfragen
            %tr
              %td
                %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:100px"}
              %td 
                %b Vereinsname
                %br
                %b Aktuelle Liga: 
                Regional
                %br 
                %b Ort: 
                Berlin
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "/pages/anfragen"} Anfragen
            %tr
              %td
                %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:100px"}
              %td 
                %b Vereinsname
                %br
                %b Aktuelle Liga: 
                Regional
                %br 
                %b Ort: 
                Berlin
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "/pages/anfragen"} Anfragen
            %tr
              %td
                %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:100px"}
              %td 
                %b Vereinsname
                %br
                %b Aktuelle Liga: 
                Regional
                %br 
                %b Ort: 
                Berlin
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "/pages/anfragen"} Anfragen
            %tr
              %td
                %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/c_scale,h_656,w_656/v1461938870/ver_image_nemmey.png", :style => "max-width:100px"}
              %td 
                %b Vereinsname
                %br
                %b Aktuelle Liga: 
                Regional
                %br 
                %b Ort: 
                Berlin
              %td#anf
                %a.btn.btn-primary.btn-lg.btn-block{:href => "/pages/anfragen"} Anfragen
  %nav#pagin
    %ul.pagination.pagination-sm
      %li.disabled
        %a{"aria-label" => "Previous", :href => "#"}
          %span{"aria-hidden" => "true"} &laquo;
      %li.active
        %a{:href => "#"}
          1
          %span.sr-only (current)
      %li
        %a{:href => "#"} 2
      %li
        %a{:href => "#"} 3 
  .container-fluid#footer
    %a.navbar-brand{:href => "#", :rel => "home", :title => "Soccertransfair"}
      %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top: -7px;"}
    .row
      .col-md-2.col-md-offset-8.col-xs-12
        = link_to 'Impressum', impressum_url , class: "main_link"
        = link_to 'Datenschutzerklärung', daten_url, class: "main_link"

app/views/users/new.html.haml
#main
  %a.navbar-brand{:href => "#", :rel => "home", :title => "Soccertransfair"}
    %img{:src => "http://res.cloudinary.com/dr68ladtn/image/upload/v1461068655/logo_lwgrxf.png", :style => "max-width:150px; margin-top:5px; margin-left:5px;"}
  %p
    %h1#bald
      Wir sind bald online!
    #trag
      Tragen Sie Ihre E-Mail Adresse ein und wir 
      %br benachrichtigen Sie sobald es Neuigkeiten gibt



  = form_for :user, url: users_path do |f|
    #field
      = f.text_field :email , class: 'emaiil', :placeholder => "E-Mail Adresse"
      = f.submit "Absenden", class: "subutton"
    - if @user.errors.any?
      #error_explanation
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg
 
    #linki 
      = link_to 'Impressum', impressum_url , class: "link"
      |
      = link_to 'Datenschutzerklärung', daten_url, class: "link"